<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Laporan;

class LaporanSeeder extends Seeder
{
    public function run()
    {
        $data = [
            [
                'judul' => 'Kerusakan Infrastruktur #1',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 1, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 1, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #2',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 2, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 2, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #3',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 3, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 3, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #4',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 4, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 4, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #5',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 5, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 5, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #6',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 6, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 6, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #7',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 7, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 7, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #8',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 8, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 8, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #9',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 9, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 9, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #10',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 10, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 10, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #11',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 11, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 11, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #12',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 12, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 12, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #13',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 13, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 13, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #14',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 14, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 14, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #15',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 15, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 15, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #16',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 16, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 16, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #17',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 17, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 17, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #18',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 18, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 18, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #19',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 19, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 19, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #20',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 20, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 20, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #21',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 21, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 21, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #22',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 22, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 22, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #23',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 23, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 23, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #24',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 24, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 24, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #25',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 25, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 25, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #26',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 26, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 26, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #27',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 27, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 27, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #28',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 28, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 28, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #29',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 29, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 29, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #30',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 30, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 30, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #31',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 31, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 31, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #32',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 32, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 32, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #33',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 33, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 33, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #34',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 34, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 34, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #35',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 35, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 35, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #36',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 36, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 36, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #37',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 37, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 37, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #38',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 38, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 38, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #39',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 39, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 39, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #40',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 40, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 40, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #41',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 41, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 41, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #42',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 42, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 42, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #43',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 43, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 43, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #44',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 44, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 44, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #45',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 45, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 45, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #46',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 46, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 46, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #47',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 47, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 47, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #48',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 48, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 48, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #49',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 49, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 49, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #50',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 50, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 50, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #51',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 51, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 51, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #52',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 52, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 52, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #53',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 53, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 53, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #54',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 54, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 54, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #55',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 55, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 55, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #56',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 56, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 56, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #57',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 57, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 57, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #58',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 58, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 58, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #59',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 59, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 59, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #60',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 60, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 60, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #61',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 61, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 61, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #62',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 62, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 62, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #63',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 63, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 63, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #64',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 64, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 64, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #65',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 65, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 65, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #66',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 66, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 66, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #67',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 67, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 67, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #68',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 68, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 68, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #69',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 69, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 69, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #70',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 70, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 70, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #71',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 71, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 71, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #72',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 72, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 72, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #73',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 73, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 73, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #74',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 74, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 74, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #75',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 75, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 75, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #76',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 76, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 76, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #77',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 77, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 77, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #78',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 78, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 78, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #79',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 79, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 79, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #80',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 80, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 80, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #81',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 81, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 81, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #82',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 82, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 82, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #83',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 83, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 83, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #84',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 84, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 84, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #85',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 85, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 85, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #86',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 86, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 86, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #87',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 87, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 87, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #88',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 88, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 88, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #89',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 89, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 89, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #90',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 90, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 90, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #91',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 91, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 91, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #92',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 92, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 92, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #93',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 93, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 93, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #94',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 94, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 94, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #95',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 95, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 95, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #96',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 96, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 96, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #97',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 97, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 97, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #98',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 98, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 98, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #99',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 99, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 99, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #100',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 100, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 100, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #101',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 101, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 101, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #102',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 102, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 102, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #103',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 103, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 103, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #104',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 104, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 104, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #105',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 105, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 105, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #106',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 106, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 106, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #107',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 107, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 107, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #108',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 108, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 108, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #109',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 109, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 109, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #110',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 110, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 110, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #111',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 111, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 111, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #112',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 112, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 112, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #113',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 113, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 113, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #114',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 114, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 114, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #115',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 115, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 115, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #116',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 116, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 116, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #117',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 117, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 117, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #118',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 118, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 118, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #119',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 119, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 119, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #120',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 120, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 120, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #121',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 121, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 121, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #122',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 122, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 122, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #123',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 123, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 123, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #124',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 124, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 124, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #125',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 125, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 125, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #126',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 126, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 126, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #127',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 127, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 127, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #128',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 128, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 128, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #129',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 129, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 129, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #130',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 130, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 130, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #131',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 131, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 131, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #132',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 132, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 132, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #133',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 133, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 133, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #134',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 134, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 134, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #135',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 135, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 135, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #136',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 136, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 136, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #137',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 137, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 137, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #138',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 138, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 138, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #139',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 139, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 139, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #140',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 140, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 140, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #141',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 141, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 141, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #142',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 142, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 142, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #143',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 143, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 143, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #144',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 144, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 144, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #145',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 145, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 145, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #146',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 146, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 146, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #147',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 147, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 147, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #148',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 148, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 148, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #149',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 149, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 149, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'judul' => 'Kerusakan Infrastruktur #150',
                'deskripsi' => 'Deskripsi kerusakan infrastruktur nomor 150, perlu segera ditangani agar tidak membahayakan masyarakat.',
                'lokasi' => 'Lokasi titik 150, Surakarta',
                'status' => 'pending',
                'foto' => null,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        foreach ($data as $item) {
            Laporan::create($item);
        }
    }
}
